quotes = ["Heh, this Gem tech is simply archaic. - Peridot S1E44",
"There appears to be an infestation of 'Stevens' in the Kindergarten. - Peridot S1E44",
"I'm reporting this! - Peridot S1E44",
"Go to Earth,' they said. 'It'll be easy,' they said. - Peridot S1E52",
"DIE, DIE, DIE, DIE, DIE, DIE, DIE, DIE, DIE, DIE, DIE, DIE! - Peridot S2E15",
"I'm gonna die here! - Peridot S2E18",
"I demand to know what this place is and where I- Oh my stars. You're going to harvest me? - Peridot S2E18",
"What's a shirt? - Peridot S2E18",
"Look, over there! Another planet to betray! - Peridot S2E18",
"I demand entry, you clod! - Peridot S3E9",
"Hello corn - Peridot S4E8",
"You know what else would be a reward? A REWARD! *highfives Lapis* - Peridot S4E8",
"Let's stay on this miserable planet, together! - Lapis S1E52",
"I'm not Lapis anymore. We're Malachite now. - Lapis S2E10",
"You do realize that I spent the last few months trapped under the ocean, right? - Lapis S3E4",
"I don't want your garbage. - Lapis S3E4",
"Thanks, but I'm not putting that on my body. - Lapis S3E15",
"I've been calling it meep morp. - Lapis S3E22",
"We're very sorry for your marriage. - Lapis S4E8",
"Why don't you put the corn in a mirror for thousands of years and then see how it feels about the table? - Lapis S4E8",
"Wait, you have healing powers? - Lapis S1E26",
"Here's my meep morp. This is a baseball bat. It reminds me of when I played baseball. This is the leaf Steven gave me. It reminds me of the time... Steven gave me a leaf. - Lapis S3E22",
"I just turned all my fingers into cats! - Steven S1E6",
"All I wanna do is see you turn into a giant woman! - Steven S1E12",
"Will you help me into my Birthday Suit? - Steven S1E12",
"I just can't believe you guys are like a bazillion years old! How do you find a cake big enough for all that many candles? - Steven S1E13",
"I'm gonna bring the ocean back... or get really thirsty trying. - Steven S1E26",
"Lapis, I'm coming up to see you, so please don't drown me. - Steven S1E26",
"You gotta take this online quiz: 'Which Crying Breakfast Friend Are You?'! - Steven S2E5",
"Wow, I want four legs too! - Steven S2E5",
"I caught a Peridot! - Steven S2E15",
"Ooh! I'm naked! - Steven S3E10",
"Humans find such fascinating ways to waste their time. - Pearl S1E11",
"Oh, Steven, you're supposed to sneeze into your antecubital fossa. - Pearl S1E36",
"I can't believe my flipping eyes! - Pearl S1E49",
"I don't understand your human relationships. So, um... goodbye! - Pearl S2E1",
"Well, yes. What other option do we have? Keep her outside on a leash? *laughs* Ha ha... Hmm... - Pearl S2E18",
"Oh, honestly, you call everyone a clod. - Pearl S3E5",
"I've modified them to accommodate less...lethal training. - Pearl S3E19",
"Our Greg is clearly the superior one. - Pearl S4E8",
"Why don't we all just marry each other. - Pearl S4E8",
"WE'LL NEVER ESCAPE, THIS IS OUR NEW HOME! - Pearl S2E3",
"It's a burrito. - Garnet S1E13",
"You have a lobster on your butt. - Garnet S1E22",
"No dinner for 1,000 years. - Garnet S1E32",
"*picks up a giant battleaxe* Never know when you might need one of these. - Garnet S1E45",
"I blame the cows. - Garnet S2E21",
"Hello, this is Mom Universe. Yes, the children are playing swords. Sorry, playing with swords. They are bleeding. Oh no, they are dead. Don't call again. Sorry, I panicked. - Garnet S1E32",
"It's a three-hour paddle home. - Garnet S1E3",
"We can't keep fighting these things forever. Well, we can, but I don't want to. - Garnet S1E44",
"I have to burn this. *unfurls scroll with mystic symbols* \nSteven: Cool! *takes a picture with his smartphone* \n*takes phone* I have to burn this, too. - Garnet S1E4",
"All comedy is derived from fear. - Garnet S1E32",
"Great job, Steven! You just saved MOST of Beach City! - Amethyst S1E2",
"I swallowed a rock. - Amethyst S1E11",
"If you're trying to flush yourself down the toilet, it won't work. Trust me, I've tried. - Amethyst S2E18",
"Wait, can Steven fly? Yeah, I think I remember that. No no, I'm thinking of Lapis. Hey, Steven! How did you learn how to fly? - Amethyst S3E6",
"I licked three bottles of cooking oil earlier. - Amethyst S4E8",
"This table has corn on it and it's beautiful and we'll defend it! - Amethyst S4E8",
"I got hit by a airplane! - Amethyst S1E16",
"*screaming* Help AH! They're gonna put me in the ground! *sobbing* No-oh Those flowers are lovely! AHH - Amethyst S1E34",
"You can't outrun me, we both have short legs! - Amethyst S1E4",
"You just got... Garneted! - Amethyst S1E23",
"I'll get you a stick of pepperoni for your birthday - Andy S4E8",
"You're a mile in the sky hanging off a floating lady! - Andy S4E8"]